---
# tasks file for roles/database
- name: database container
  docker_container:
    name: database
    image: imanebenmansour/correction-tp1-master_database
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_DB: db
