language: java
script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=devops-epf --file ./simple-api/pom.xml
  #- mvn clean verify --file ./simple-api/pom.xml
  #
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  #
  - docker build -t imanebenmansour/correction-tp1-master_database database
  - docker build -t imanebenmansour/correction-tp1-master_backend simple-api
  - docker build -t imanebenmansour/correction-tp1-master_httpd httpd

  - docker push imanebenmansour/correction-tp1-master_database
  - docker push imanebenmansour/correction-tp1-master_backend
  - docker push imanebenmansour/correction-tp1-master_httpd
cache:
  directories:
    - $HOME/.m2
services:
  - docker
addons:
  sonarcloud:
    organization: "imaneb29207"
    token: "$SONARCLOUD_TOKEN"