---
# tasks file for roles/front
- name: Launch front
  docker_container: 
   name: frontend
   image: imanebenmansour/correction-tp1-master_front
   state: started
   pull: yes
   networks:
    - name: app-network
